# fly.toml app configuration file generated for specialblend on 2024-10-23T00:24:57-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'specialblend'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
